"""Initial schema

Revision ID: e922bf1c41ff
Revises: 
Create Date: 2026-08-24 15:54:41.510657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e922bf1c41ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_agent_tokens_active'), table_name='agent_tokens', postgresql_where='((revoked = false) AND (consumed_at IS NULL))')
    op.drop_constraint(op.f('agent_tokens_max_txn_paise_check'), 'agent_tokens', type_='check')
    op.create_check_constraint('check_agent_txn_limit_positive', 'agent_tokens', 'max_txn_paise > 0')
    op.drop_index(op.f('idx_audit_events_order'), table_name='audit_events')
    op.drop_index(op.f('idx_audit_events_payment'), table_name='audit_events')
    op.drop_index(op.f('idx_audit_events_session'), table_name='audit_events')
    op.drop_index(op.f('idx_audit_events_status'), table_name='audit_events')
    op.drop_index(op.f('uq_audit_events_captured_once'), table_name='audit_events', postgresql_where="(status = 'captured'::audit_status_enum)")
    op.drop_constraint(op.f('audit_events_intent_id_fkey'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('audit_events_session_id_fkey'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('audit_events_decision_id_fkey'), 'audit_events', type_='foreignkey')
    op.create_foreign_key(None, 'audit_events', 'decisions', ['decision_id'], ['decision_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'audit_events', 'intents', ['intent_id'], ['intent_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'audit_events', 'sessions', ['session_id'], ['session_id'], ondelete='RESTRICT')
    op.alter_column('cart_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_cart_items_session'), table_name='cart_items', postgresql_where='(removed_at IS NULL)')
    op.drop_constraint(op.f('cart_items_price_at_add_paise_check'), 'cart_items', type_='check')
    op.drop_constraint(op.f('cart_items_qty_check'), 'cart_items', type_='check')
    op.create_check_constraint('check_cart_price_positive', 'cart_items', 'price_at_add_paise > 0')
    op.create_check_constraint('check_cart_qty_positive', 'cart_items', 'qty > 0')
    op.drop_index(op.f('idx_decisions_decision'), table_name='decisions')
    op.drop_index(op.f('idx_decisions_intent'), table_name='decisions')
    op.drop_constraint(op.f('decisions_intent_id_fkey'), 'decisions', type_='foreignkey')
    op.create_foreign_key(None, 'decisions', 'intents', ['intent_id'], ['intent_id'], ondelete='RESTRICT')
    op.drop_index(op.f('idx_intents_action_type'), table_name='intents')
    op.drop_index(op.f('idx_intents_session'), table_name='intents')
    op.drop_constraint(op.f('intents_session_id_fkey'), 'intents', type_='foreignkey')
    op.create_foreign_key(None, 'intents', 'sessions', ['session_id'], ['session_id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('merchant_config_max_discount_pct_check'), 'merchant_config', type_='check')
    op.drop_constraint(op.f('merchant_config_max_order_paise_check'), 'merchant_config', type_='check')
    op.drop_constraint(op.f('merchant_config_max_upsell_attempts_check'), 'merchant_config', type_='check')
    op.drop_constraint(op.f('merchant_config_upsell_cooldown_sec_check'), 'merchant_config', type_='check')
    op.create_check_constraint('check_discount_range', 'merchant_config', 'max_discount_pct BETWEEN 0 AND 100')
    op.create_check_constraint('check_max_order_positive', 'merchant_config', 'max_order_paise > 0')
    op.create_check_constraint('check_upsell_attempts_positive', 'merchant_config', 'max_upsell_attempts >= 0')
    op.create_check_constraint('check_upsell_cooldown_positive', 'merchant_config', 'upsell_cooldown_sec >= 0')
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_promotable'), table_name='products', postgresql_where='(is_promotable = true)')
    op.drop_index(op.f('idx_products_style_tags'), table_name='products', postgresql_using='gin')
    op.drop_constraint(op.f('products_currency_check'), 'products', type_='check')
    op.drop_constraint(op.f('products_price_paise_check'), 'products', type_='check')
    op.drop_constraint(op.f('products_shipping_eta_days_check'), 'products', type_='check')
    op.drop_constraint(op.f('products_stock_qty_check'), 'products', type_='check')
    op.create_check_constraint('check_currency_inr', 'products', "currency = 'INR'")
    op.create_check_constraint('check_price_positive', 'products', 'price_paise > 0')
    op.create_check_constraint('check_shipping_non_negative', 'products', 'shipping_eta_days >= 0')
    op.create_check_constraint('check_stock_non_negative', 'products', 'stock_qty >= 0')
    op.drop_index(op.f('idx_sessions_merchant_status'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_started_at'), table_name='sessions')
    op.drop_column('sessions', 'chat_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('chat_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_sessions_started_at'), 'sessions', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('idx_sessions_merchant_status'), 'sessions', ['merchant_id', 'status'], unique=False)
    op.drop_constraint('check_stock_non_negative', 'products', type_='check')
    op.drop_constraint('check_shipping_non_negative', 'products', type_='check')
    op.drop_constraint('check_price_positive', 'products', type_='check')
    op.drop_constraint('check_currency_inr', 'products', type_='check')
    op.create_check_constraint(op.f('products_stock_qty_check'), 'products', 'stock_qty >= 0')
    op.create_check_constraint(op.f('products_shipping_eta_days_check'), 'products', 'shipping_eta_days >= 0')
    op.create_check_constraint(op.f('products_price_paise_check'), 'products', 'price_paise > 0')
    op.create_check_constraint(op.f('products_currency_check'), 'products', "currency = 'INR'::text")
    op.create_index(op.f('idx_products_style_tags'), 'products', ['style_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_products_promotable'), 'products', ['is_promotable'], unique=False, postgresql_where='(is_promotable = true)')
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    op.drop_constraint('check_upsell_cooldown_positive', 'merchant_config', type_='check')
    op.drop_constraint('check_upsell_attempts_positive', 'merchant_config', type_='check')
    op.drop_constraint('check_max_order_positive', 'merchant_config', type_='check')
    op.drop_constraint('check_discount_range', 'merchant_config', type_='check')
    op.create_check_constraint(op.f('merchant_config_upsell_cooldown_sec_check'), 'merchant_config', 'upsell_cooldown_sec >= 0')
    op.create_check_constraint(op.f('merchant_config_max_upsell_attempts_check'), 'merchant_config', 'max_upsell_attempts >= 0')
    op.create_check_constraint(op.f('merchant_config_max_order_paise_check'), 'merchant_config', 'max_order_paise > 0')
    op.create_check_constraint(op.f('merchant_config_max_discount_pct_check'), 'merchant_config', 'max_discount_pct >= 0::numeric AND max_discount_pct <= 100::numeric')
    op.drop_constraint(None, 'intents', type_='foreignkey')
    op.create_foreign_key(op.f('intents_session_id_fkey'), 'intents', 'sessions', ['session_id'], ['session_id'])
    op.create_index(op.f('idx_intents_session'), 'intents', ['session_id', 'submitted_at'], unique=False)
    op.create_index(op.f('idx_intents_action_type'), 'intents', ['action_type'], unique=False)
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.create_foreign_key(op.f('decisions_intent_id_fkey'), 'decisions', 'intents', ['intent_id'], ['intent_id'])
    op.create_index(op.f('idx_decisions_intent'), 'decisions', ['intent_id'], unique=False)
    op.create_index(op.f('idx_decisions_decision'), 'decisions', ['decision'], unique=False)
    op.drop_constraint('check_cart_qty_positive', 'cart_items', type_='check')
    op.drop_constraint('check_cart_price_positive', 'cart_items', type_='check')
    op.create_check_constraint(op.f('cart_items_qty_check'), 'cart_items', 'qty > 0')
    op.create_check_constraint(op.f('cart_items_price_at_add_paise_check'), 'cart_items', 'price_at_add_paise > 0')
    op.create_index(op.f('idx_cart_items_session'), 'cart_items', ['session_id'], unique=False, postgresql_where='(removed_at IS NULL)')
    op.alter_column('cart_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('audit_events_decision_id_fkey'), 'audit_events', 'decisions', ['decision_id'], ['decision_id'])
    op.create_foreign_key(op.f('audit_events_session_id_fkey'), 'audit_events', 'sessions', ['session_id'], ['session_id'])
    op.create_foreign_key(op.f('audit_events_intent_id_fkey'), 'audit_events', 'intents', ['intent_id'], ['intent_id'])
    op.create_index(op.f('uq_audit_events_captured_once'), 'audit_events', ['razorpay_payment_id'], unique=True, postgresql_where="(status = 'captured'::audit_status_enum)")
    op.create_index(op.f('idx_audit_events_status'), 'audit_events', ['status'], unique=False)
    op.create_index(op.f('idx_audit_events_session'), 'audit_events', ['session_id', 'event_at'], unique=False)
    op.create_index(op.f('idx_audit_events_payment'), 'audit_events', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('idx_audit_events_order'), 'audit_events', ['razorpay_order_id'], unique=False)
    op.drop_constraint('check_agent_txn_limit_positive', 'agent_tokens', type_='check')
    op.create_check_constraint(op.f('agent_tokens_max_txn_paise_check'), 'agent_tokens', 'max_txn_paise > 0')
    op.create_index(op.f('idx_agent_tokens_active'), 'agent_tokens', ['token_id'], unique=False, postgresql_where='((revoked = false) AND (consumed_at IS NULL))')
    # ### end Alembic commands ###
